name: Crawl KdB

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Setup Rust
    #   run: |
    #     rustup set profile minimal
    #     rustup install stable
    #     rustup override set stable
    #     rustup component add clippy      

    - uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --release

    - name: Run binary
      run: ./target/release/kdb-crawler

    # - name: Upload release asset
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: ./dist/kdb.json